wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.9
    cli_version: 0.15.7
    framework: huggingface
    huggingface_version: 4.24.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1690532744.264666
    t:
      1:
      - 1
      - 2
      - 3
      - 11
      - 41
      - 49
      - 55
      3:
      - 23
      4: 3.10.9
      5: 0.15.7
      6: 4.24.0
      8:
      - 3
      - 5
      - 9
